# Generated by Django 4.2.6 on 2023-11-11 21:02

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('Segunda', 'Segunda-Feira'), ('Terca', 'Terça-Feira'), ('Quarta', 'Quarta-Feira'), ('Quinta', 'Quinta-Feira'), ('Sexta', 'Sexta-Feira'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='img')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.interval')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_days', to='restaurant.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('insta', 'Instagram'), ('whats', 'Whatsapp'), ('face', 'Facebook'), ('ifood', 'Ifood'), ('tnl', 'Tonolucro')], max_length=20)),
                ('information', models.CharField(max_length=100)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='restaurant.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(max_length=255)),
                ('number', models.IntegerField(unique=True)),
                ('postal_code', models.CharField(unique=True, validators=[django.core.validators.RegexValidator(message='Invalid postal code!', regex='^(\\d{5}(\\-\\d{3})?)?$')])),
                ('restaurant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_address', to='restaurant.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
