# Generated by Django 4.2.6 on 2023-11-05 22:49

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Segunda', 'Segunda-Feira'), ('Terca', 'Terça-Feira'), ('Quarta', 'Quarta-Feira'), ('Quinta', 'Quinta-Feira'), ('Sexta', 'Sexta-Feira'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('open', models.CharField(validators=[django.core.validators.RegexValidator(message='Incorrect Format hh:mm', regex='^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$')])),
                ('close', models.CharField(validators=[django.core.validators.RegexValidator(message='Incorrect Format hh:mm', regex='^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$')])),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.interval')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_days', to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('insta', 'Instagram'), ('whats', 'Whatsapp'), ('face', 'Facebook'), ('ifood', 'Ifood'), ('tnl', 'Tonolucro')], max_length=20)),
                ('information', models.CharField(max_length=100)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(max_length=255)),
                ('number', models.IntegerField(unique=True)),
                ('postal_code', models.CharField(unique=True, validators=[django.core.validators.RegexValidator(message='Invalid postal code!', regex='^(\\d{5}(\\-\\d{3})?)?$')])),
                ('restaurant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_address', to='restaurant.restaurant')),
            ],
        ),
    ]
